# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b1621ef60271272bf0f3bbab6d619174074b1cb82b6784dc9ffabeaabf2dc40d2184124c2e7e3ad999ec65c50c902de24e9b3fa519513bbe38897f4bfa5db4b

test:
  secret_key_base: 77d354ac0850c023496345d5c5b37c1d2297e5030974fe6bffd0fa165289e35bc2c4a3d96e9aa8df98f65131bab3015bb0301c8a91a1cf922fb851ca709b4fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
